### ISSUE TITLE
Move Banner role after Harden role

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/freeipa-server-packer#119]
# 🐛 Summary #

The banner role sets the custom CISA banners to `/etc/motd`, `/etc/issue`, and `/etc/issue.net`. However, the harden role reverts them to default generic CIS Benchmarks settings. The task for running the banner role should be moved from `base.yml` to the end of `harden.yml`

## To reproduce ##

1. Build AMI
2. Banner is set to default CIS Benchmarks generic banner

## Expected behavior ##

Banner should be CISA custom banner

**Comment by jsf9k** [comment]
The other option is to override some defaults in the hardening role so that it puts our banner in place.  I will have to look into it to figure out which approach is best.

**Comment by bra1ncramp** [comment]
I suppose we could just not run `tasks/issue.yml`

https://github.com/cisagov/ansible-role-hardening-2/blob/master/tasks/issue.yml
