### ISSUE TITLE
FreeIPA upgrade did not go smoothly

### ISSUE THREAD

**Issue by jsf9k** [cisagov/freeipa-server-packer#32]
# 🐛 Bug Report

A few weeks ago I attempted a FreeIPA upgrade using [these instructions](https://github.com/cisagov/cool-system/wiki/Upgrading-the-FreeIPA-cluster) and it did not go smoothly.  @dav3r and I ended up having to re-install the production FreeIPA cluster.

I got confirmation from someone at RedHat who is assigned to the FreeIPA project that I am upgrading in the approved way, and this upgrade has worked in the past, so something fishy is going on.

I need to:
1. Determine why this happened.
1. Determine how to correct the issue.  This may require [a bug report](https://pagure.io/freeipa/issues) and/or a [pull request](https://github.com/freeipa/freeipa) to [the FreeIPA project](https://pagure.io/freeipa).
1. Verify in our staging environment that I can smoothly upgrade using the instructions linked to above.
1. Push required changes to our production environment.

## Expected behavior

The FreeIPA upgrade should go smoothly.

**Comment by jsf9k** [comment]
See [the FreeIPA issue I created](https://pagure.io/freeipa/issue/8470).

**Comment by jsf9k** [comment]
I am testing by performing the following tests:

- [x] :heavy_check_mark: Perform a fresh FreeIPA cluster install in staging (all three nodes, existing staging AMI)
- [x] :heavy_check_mark: Perform a full FreeIPA cluster upgrade in staging (all three nodes, existing staging AMI)
- [x] :heavy_check_mark: Rebuild staging AMI and then perform a full FreeIPA cluster upgrade in staging (all three nodes, new staging AMI)
- [x] :heavy_check_mark: Install `ipa1` and `ipa2` in production (existing production AMI)
- [x] :heavy_check_mark: Rebuild production AMI and then perform a full FreeIPA cluster upgrade in production (all three nodes, new staging AMI)

**Comment by jsf9k** [comment]
The "Install `ipa1` and `ipa2` in production (existing production AMI)" test is failing just like it did before.  I'm trying to determine what the differences are between our staging and production environments. :disappointed:

**Comment by jsf9k** [comment]
> The "Install `ipa1` and `ipa2` in production (existing production AMI)" test is failing just like it did before. I'm trying to determine what the differences are between our staging and production environments.

Restarting the whole shebang (`systemctl restart freeipa`) appears to have fixed the issue I was seeing in our production environment.

**Comment by jsf9k** [comment]
I was able to perform a full upgrade in production, although I did have to run `systemctl restart freeipa` on `ipa1` after upgrading it to allow `ipa2` to replicate against it.  It would be nice to know exactly what is failing, so we can fix it or try to get it fixed in FreeIPA, but I haven't been able to determine that.  I will update [the FreeIPA issue](https://pagure.io/freeipa/issue/8470) to let them know that the problem isn't fixed but I have a workaround.

@dav3r, do you concur that we can close this issue?

**Comment by dav3r** [comment]
> @dav3r, do you concur that we can close this issue?

Yes, I'm good with closing this issue- we can always re-open it later if necessary.

Thanks for all of your hard work getting us to this point! 🥇

**Comment by jsf9k** [comment]
Closing this issue for now, since we now know how to work around the issue.  If we ever figure out exactly what is going wrong we can reopen this issue or create another one.
