### ISSUE TITLE
The FreeIPA AMIs should be hardened

### ISSUE THREAD

**Issue by jsf9k** [cisagov/freeipa-server-packer#33]
# 🚀 Feature Proposal

The FreeIPA AMIs should have the ability to be hardened.

## Motivation

In the COOL, the FreeIPA instances are part of the static environment and therefore must be hardened.

## Pitch

Ideally the Packer playbook would apply a hardening Ansible role at the end of the AMI building process.

## Remaining items
- [x] Ensure AIDE is installed
- [x] Ensure filesystem integrity is regularly checked
- [x] Ensure authentication required for single user mode
- [x] Ensure chrony is configured
- [x] Ensure packet redirect sending is disabled
- [x] Ensure source routed packets are not accepted
- [x] Ensure suspicious packets are logged
- [x] Ensure IPv4/IPv6 loopback traffic is configured
- [x] Ensure permissions on all logfiles are configured
- [x] Ensure password creation requirements are configured - retry=3
- [x] Ensure system accounts are secured and non-login
- [x] Ensure access to the su command is restricted
- [x] Ensure users' home directories permissions are 750 or more restrictive

**Comment by jsf9k** [comment]
We have been told to follow the CIS guidance.  In this case, this is the [CIS distribution-independent guidance](https://www.cisecurity.org/benchmark/distribution_independent_linux/).

**Comment by jsf9k** [comment]
See [this branch in cisagov/freeipa-server-packer](https://github.com/cisagov/freeipa-server-packer/tree/feature/hardening) and [cisagov/ansible-role-hardening](https://github.com/cisagov/ansible-role-hardening).

**Comment by dav3r** [comment]
Hardening guide: [CIS_Distribution_Independent_Linux_Benchmark_v2.0.0.pdf](https://app.zenhub.com/files/195118196/26379e5a-c0dc-4ac5-97d6-de600565bdb9/download)

**Comment by dav3r** [comment]
@jsf9k has created this draft PR: https://github.com/cisagov/freeipa-server-packer/pull/35

**Comment by jsf9k** [comment]
I'm going to close this issue since the initial hardening PR was merged some time ago.  If any new details come up we can create new issues for them.
